Repository cloudevents/sdk-javascript, pull requests merged in 2020-06, with the labels that each got.

#200 fix: fix references to constants - remove .js extension
  .gitignore
  src/lib/bindings/http/emitter_binary.js
  src/lib/bindings/http/emitter_structured.js
  src/lib/bindings/http/receiver_binary.js
  src/lib/bindings/http/receiver_structured.js
  src/lib/bindings/http/v03/emitter_binary_0_3.js
  src/lib/bindings/http/v03/receiver_binary_0_3.js
  src/lib/bindings/http/v03/receiver_structured_0_3.js
  src/lib/bindings/http/v1/emitter_binary_1.js
  src/lib/bindings/http/v1/receiver_structured_1.js
  src/lib/bindings/http/validation/binary.js
  src/lib/bindings/http/validation/commons.js
  src/lib/bindings/http/validation/structured.js
  src/lib/cloudevent.ts
Labels: fix

#202 fix: add correct types to improve usage in TypeScript projects
  package-lock.json
  package.json
  src/lib/bindings/http/http_emitter.ts
  src/lib/bindings/http/http_receiver.ts
  src/lib/cloudevent.ts
  test-ts/cloud_event_test.ts
  test-ts/http_emitter_test.ts
  test-ts/http_receiver_test.ts
  tsconfig.json
Labels: bug

#207 lib: remove specversion from the attributes in receiver.accept()
  src/lib/bindings/http/http_receiver.ts
Labels: fix, typescript

#217 docs: generate api documentation as a GitHub workflow
  .github/workflows/api-docs.yaml
  package-lock.json
  package.json
  src/lib/formats/json/parser.ts
  tsconfig.json
Labels: docs

#214 feat: pass extension into the constructor.
  src/lib/cloudevent.ts
  src/lib/extensions.ts
  src/lib/v03/index.ts
  src/lib/v1/index.ts
  test-ts/cloud_event_test.ts
Labels: enhancement

#224 docs(README): fix wrong order of arguments in the accept example
  README.md
Labels: docs

#221 chore: adds the return type for the extension methods
  src/lib/cloudevent.ts
Labels: fix
