Repository cloudevents/sdk-javascript, pull requests merged in 2020-05, with the labels that each got.

#106 fix: [backport] support mTLS in 1.0 Binary and Structured emitters
  lib/bindings/http/emitter_binary.js
  lib/bindings/http/emitter_structured.js
  test/http_binding_1.js
  v1/index.js
Labels: v1.x.y-backport

#126 feat(unmarshaller)!: remove asynchronous 0.3 unmarshaller API
  lib/bindings/http/unmarshaller.js
  test/bindings/http/unmarshaller_0_3_tests.js
Labels: enhancement, spec0.3

#131 test: use header constants in receiver tests
  test/bindings/http/receiver_binary_0_3_tests.js
  test/bindings/http/receiver_binary_1_tests.js
Labels: test, transport/http

#122 chore: Modify CI to also build backport branch(es)
  .travis.yml
Labels: ci, stalled, v1.x.y-backport

#134 fix: ensure binary events can handle no content-type header
  lib/bindings/http/receiver_binary.js
  lib/bindings/http/receiver_binary_1.js
  test/bindings/http/promiscuous_receiver_test.js
Labels: bug, transport/http

#138 docs: update README and examples with new API
  README.md
  examples/express-ex/README.md
  examples/express-ex/index.js
  examples/typescript-ex/src/index.ts
Labels: docs

#139 fix: throw "no cloud event detected" if one can't be read
  lib/bindings/http/http_receiver.js
  test/bindings/http/promiscuous_receiver_test.js
Labels: enhancement

#105 docs: add instructions and details to contributors guide
  CONTRIBUTING.md
  maintainer_guidelines.md
  pr_guidelines.md
Labels: discussion, docs

#151 feat: add ValidationError type extending TypeError
  lib/bindings/http/http_receiver.js
  lib/bindings/http/receiver_binary.js
  lib/bindings/http/receiver_binary_0_3.js
  lib/bindings/http/receiver_structured.js
  lib/bindings/http/unmarshaller.js
  lib/cloudevent.js
  lib/formats/json/parser.js
  lib/specs/spec_0_3.js
  lib/specs/spec_1.js
  lib/validation_error.js
  test/bindings/http/promiscuous_receiver_test.js
  test/bindings/http/receiver_binary_0_3_tests.js
  test/bindings/http/receiver_binary_1_tests.js
  test/bindings/http/receiver_structured_0_3_test.js
  test/bindings/http/receiver_structured_1_test.js
  test/bindings/http/unmarshaller_0_3_tests.js
  test/formats/json/parser_test.js
  test/spec_0_3_tests.js
  test/spec_1_tests.js
Labels: enhancement

#141 feat!: expose a version agnostic event emitter
  README.md
  index.js
  lib/bindings/http/emitter_binary.js
  lib/bindings/http/emitter_binary_0_3.js
  lib/bindings/http/emitter_binary_1.js
  lib/bindings/http/emitter_structured.js
  lib/bindings/http/http_emitter.js
  test/bindings/http/http_emitter_test.js
  test/bindings/http/receiver_structured_0_3_test.js
  test/bindings/http/receiver_structured_1_test.js
  test/http_binding_0_3.js
  test/http_binding_1.js
  test/sdk_test.js
  v03/index.js
  v1/index.js
Labels: enhancement, transport/http

#161 lib: expose constants as a top-level export
  index.js
  lib/bindings/http/constants.js
  lib/bindings/http/http_receiver.js
  lib/bindings/http/unmarshaller.js
  test/bindings/http/unmarshaller_0_3_tests.js
  test/constants_test.js
  test/spec_0_3_tests.js
Labels: enhancement

#172 lib!: change CloudEvent to use direct object notation and get/set properties
  .jsdoc.json
  README.md
  docs/BinaryHTTPEmitter.html
  docs/BinaryHTTPReceiver.html
  docs/CloudEvent.html
  docs/HTTPEmitter.html
  docs/HTTPReceiver.html
  docs/StructuredHTTPEmitter.html
  docs/StructuredHTTPReceiver.html
  docs/ValidationError.html
  docs/bindings_http_emitter_binary.js.html
  docs/bindings_http_emitter_structured.js.html
  docs/bindings_http_http_emitter.js.html
  docs/bindings_http_http_receiver.js.html
  docs/bindings_http_receiver_binary.js.html
  docs/bindings_http_receiver_structured.js.html
  docs/bindings_http_v03_emitter_binary_0_3.js.html
  docs/bindings_http_v1_emitter_binary_1.js.html
  docs/bindings_http_validation_validation_error.js.html
  docs/cloudevent.js.html
  docs/formats_json_parser.js.html
  docs/global.html
  docs/index.html
  lib/bindings/http/emitter_binary.js
  lib/bindings/http/http_emitter.js
  lib/bindings/http/v03/emitter_binary_0_3.js
  lib/bindings/http/v03/receiver_binary_0_3.js
  lib/bindings/http/v03/spec_0_3.js
  lib/bindings/http/v1/emitter_binary_1.js
  lib/bindings/http/v1/receiver_binary_1.js
  lib/bindings/http/v1/receiver_structured_1.js
  lib/bindings/http/v1/spec_1.js
  lib/bindings/http/validation/binary.js
  lib/bindings/http/validation/structured.js
  lib/bindings/http/validation/validation_error.js
  lib/cloudevent.js
  lib/formats/json/parser.js
  plugins/ignore-typedef.js
  test/bindings/http/http_emitter_test.js
  test/bindings/http/promiscuous_receiver_test.js
  test/bindings/http/receiver_binary_0_3_tests.js
  test/bindings/http/receiver_binary_1_tests.js
  test/bindings/http/receiver_structured_0_3_test.js
  test/bindings/http/receiver_structured_1_test.js
  test/cloud_event_test.js
  test/http_binding_0_3.js
  test/http_binding_1.js
  test/sdk_test.js
  test/spec_0_3_tests.js
  test/spec_1_tests.js
Labels: enhancement

#186 lib: make HTTPEmitter headers method a property of the class
  lib/bindings/http/http_emitter.js
  test/bindings/http/http_emitter_test.js
Labels: enhancement

#177 docs: add maintainer guidelines for landing PRs
  maintainer_guidelines.md
Labels: docs

#181 chore: add GitHub action for CI on master and prs
  .github/workflows/nodejs-ci-action.yml
  .travis.yml
  README.md
Labels: ci

#185 chore: add coverage GitHub action
  .github/workflows/codacy-coverage-reporter.yml
Labels: ci

#193 chore: CI workflow to only upload report if CODACY_PROJECT_TOKEN is set
  .github/workflows/codacy-coverage-reporter.yml
  .github/workflows/nodejs-ci-action.yml
  package.json
Labels: ci
