Repository cloudevents/sdk-javascript, pull requests merged in 2020-07, with the labels that each got.

#235 chore(actions): don't auto-close stale issues and pull requests
  .github/workflows/stale.yml
Labels: chore/actions

#239 fix: ensure that the HTTP receiver sanitizes headers in accept()
  src/transport/receiver.ts
  test/http_receiver_test.ts
Labels: type/bug

#243 chore: bump GH stale action to v3
  .github/workflows/stale.yml
Labels: chore/actions

#238 test: implement the cucumber conformance tests
  .gitmodules
  cucumber.js
  package-lock.json
  package.json
  src/parsers/index.ts
  src/transport/http/binary_receiver.ts
  src/transport/http/headers.ts
  test/conformance/steps.ts
  test/integration/cloud_event_test.ts
  test/integration/constants_test.ts
  test/integration/http_binding_03.ts
  test/integration/http_binding_1.ts
  test/integration/http_emitter_test.ts
  test/integration/http_receiver_test.ts
  test/integration/parser_test.ts
  test/integration/receiver_binary_03_tests.ts
  test/integration/receiver_binary_1_tests.ts
  test/integration/receiver_structured_0_3_test.ts
  test/integration/receiver_structured_1_test.ts
  test/integration/sdk_test.ts
  test/integration/spec_03_tests.ts
  test/integration/spec_1_tests.ts
  test/integration/utilities_test.ts
Labels: module/test, spec/1.0, type/enhancement

#234 Validate a Cloud Event on creation and make it read only with a method to augment it
  src/event/cloudevent.ts
  src/event/v03/cloudevent.ts
  src/event/v1/cloudevent.ts
  test/integration/cloud_event_test.ts
  test/integration/http_binding_03.ts
  test/integration/http_binding_1.ts
  test/integration/spec_03_tests.ts
  test/integration/spec_1_tests.ts
Labels: version/3.x

#252 docs: clean up spec compliance table on README.md
  README.md
Labels: module/docs

#259 fix: do not require an HTTP body on incoming binary messages
  src/transport/http/binary_receiver.ts
  src/transport/http/structured_receiver.ts
  src/transport/receiver.ts
  test/integration/http_receiver_test.ts
  test/integration/receiver_binary_03_tests.ts
  test/integration/receiver_binary_1_tests.ts
Labels: module/transport/http, type/fix

#260 feat: use npm name cloudevents
  README.md
  package.json
Labels: module/lib, module/releases

#271 lib: change Receiver#accept() to be static Receiver.accept
  src/transport/receiver.ts
  test/conformance/steps.ts
  test/integration/http_receiver_test.ts
Labels: module/lib, module/transport/http, type/enhancement, version/3.x

#269 refactor: combine all parsers into a single file
  src/parsers.ts
  src/parsers/base64.ts
  src/parsers/date.ts
  src/parsers/index.ts
  src/parsers/json.ts
  src/parsers/mapped.ts
  src/parsers/parser.ts
  src/parsers/pass_through.ts
  test/integration/parser_test.ts
Labels: chore/refactor

#268 chore: add vscode task JSON and GitHub issue/pr templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull-request-template.md
  .vscode/tasks.json
Labels: chore/actions

#267 chore: consolidate HTTP parsers and header maps into single files
  src/transport/http/binary_receiver.ts
  src/transport/http/structured_receiver.ts
  src/transport/http/v03.ts
  src/transport/http/v03/headers.ts
  src/transport/http/v03/index.ts
  src/transport/http/v1.ts
  src/transport/http/v1/headers.ts
  src/transport/http/v1/index.ts
Labels: chore/refactor

#251 lib: validate extension values
  src/event/cloudevent.ts
  src/event/validation.ts
  test/integration/http_emitter_test.ts
  test/integration/spec_1_tests.ts
Labels: module/lib, type/enhancement

#281 fix: ensure that event data can be an array, number, boolean or null
  src/event/schemas.ts
  test/integration/cloud_event_test.ts
Labels: module/lib, spec/0.3, spec/1.0, type/fix

#285 fix: ensure that data encoded as base64 is parsed as an object
  src/transport/http/binary_receiver.ts
  src/transport/http/structured_receiver.ts
  test/integration/receiver_binary_03_tests.ts
  test/integration/receiver_structured_0_3_test.ts
Labels: module/lib, module/transport/http, spec/0.3, type/fix

#293 chore(release): add postinstall script to warn users of name change
  README.md
  package.json
  postinstall/message.js
Labels: module/docs, module/releases, type/enhancement, version/2.x
