Repository cloudevents/sdk-javascript, pull requests merged in 2020-09, with the labels that each got.

#330 src(event)!: make the event's time property only a string
  src/event/cloudevent.ts
  src/event/interfaces.ts
  src/event/schemas.ts
  src/event/spec.ts
  src/message/http/headers.ts
  src/parsers.ts
  test/integration/cloud_event_test.ts
  test/integration/http_binding_03.ts
  test/integration/http_binding_1.ts
  test/integration/http_emitter_test.ts
  test/integration/message_test.ts
  test/integration/spec_03_tests.ts
  test/integration/spec_1_tests.ts
Labels: module/lib, type/enhancement, version/4.x

#334 chore(example): Replaced body parser with express JSON parser
  examples/express-ex/index.js
  examples/express-ex/package.json
Labels: module/examples, type/enhancement

#328 feat: add a constructor parameter for loose validation
  src/event/cloudevent.ts
  src/event/validation.ts
  src/message/http/headers.ts
  src/message/http/index.ts
  test/integration/cloud_event_test.ts
  test/integration/message_test.ts
Labels: module/lib, type/enhancement, version/3.x

#337 docs: update README with maintainer names
  README.md
Labels: module/docs

#329 chore: add an automated GH action for releases
  .github/workflows/release-please.yml
Labels: chore/actions, module/releases, type/enhancement

#342 feat: add emitterFactory and friends
  package-lock.json
  package.json
  src/index.ts
  src/message/http/index.ts
  src/transport/emitter.ts
  src/transport/http/binary_emitter.ts
  src/transport/http/index.ts
  src/transport/http/structured_emitter.ts
  test/integration/emitter_factory_test.ts
  test/integration/http_binding_03.ts
  test/integration/http_binding_1.ts
  test/integration/http_emitter_test.ts
  test/integration/message_test.ts
Labels: module/lib, module/transport/http, type/enhancement, version/4.x
